# Generated by Django 2.2.6 on 2019-11-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date time')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp max')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp min')),
                ('humidity', models.IntegerField(verbose_name='Humidity')),
                ('wind', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wind')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.City')),
            ],
        ),
    ]
